site_name: Tech Vault
site_description: Tech Vault Site -  A list of many interview questions & real-world challenges in Tech!
site_url: https://moabukar.github.io/tech-vault-site/
site_author: Mo Abukar

repo_url: https://github.com/moabukar/tech-vault-site
dev_addr: "127.0.0.1:8000"
docs_dir: docs
theme: 
  # name: material
  name: dracula
  include_sidebar: true
  # custom_dir: overrides
  extra_css:
    - assets/stylesheets/custom.css

  features:
    - navigation.tabs
    - navigation.sections
    - toc.integrate
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/toggle-switch-off-outline 
        name: Switch to dark mode
      primary: indigo
      accent: indigo
    - scheme: slate 
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode    
      primary: dark blue
      accent: lime
  i18n:
    prev: 'Previous'
    next: 'Next'

extra_javascript:
  - assets/js/hljs/highlight.pack.js # Download from https://highlightjs.org/download/ and enable YAML, TOML and Dockerfile
  - assets/js/extra.js

plugins:
  - search
  # - exclude:
  #     glob:
  #       - "**/include-*.md"
  - git-revision-date
  # - pdf-export:
  #     combined: true

markdown_extensions:
  - meta
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets:
      check_paths: true
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  # - toc:
  #     permalink: true

nav:
- Home: index.md
- DevOps:
    - Linux:
        - Questions: devops/linux/questions.md
    - Networking:
        - Questions: devops/networking/questions.md
    - Git:
        - Questions: devops/git/questions.md
    - AWS:
        - Questions: devops/aws/questions.md
    - Azure:
        - Questions: devops/azure/questions.md
    - Terraform:
        - Questions: devops/terraform/questions.md
    - Docker & K8s:
        - Questions: devops/docker-k8s/questions.md
    - Ansible:
        - Questions: devops/ansible/questions.md
    - CICD:
        - Questions: devops/cicd/questions.md
    - DevOps Methodology:
        - Questions: devops/methodology/questions.md
    - Monitoring:
        - Questions: devops/monitoring/questions.md
- System Design:
    - CDN & Caching: system-design/cdn-caching.md
    - Database: system-design/database.md
- Software Engineering:
    - General:
        - Questions: software-engineering/general/questions.md
    - Golang:
        - Questions: software-engineering/golang/questions.md
    - Python:
        - Questions: software-engineering/python/questions.md
    - Java:
        - Questions: software-engineering/java/questions.md
    - JavaScript:
        - Questions: software-engineering/javascript/questions.md

- Contribute: CONTRIBUTING.md
- Code of Conduct: CODE_OF_CONDUCT.md

copyright: |
  &copy; 2023 <a href="https://github.com/moabukar"  target="_blank" rel="noopener">Mohamed Abukar</a>

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/moabukar
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/moabukar_1
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/moabukar/
